- Gemfile.lock
- app/models/project.rb
- db/migrate/20230301195749_create_projects.rb
- test/models/project_test.rb
> project model created

- app/models/slot.rb
- db/migrate/20230301200143_create_slots.rb
- db/schema.rb
- test/models/slot_test.rb
criado arquivo app/models/slot.rb
criado arquivo db/migrate/20230301200143_create_slots.rb
> model slot.rb com validações criado

- app/models/project.rb
> project model changed

- Gemfile
- Gemfile.lock
- app/models/slot.rb
- db/seeds.rb
Seeds criar com a gem faker e tirei a validação no models de "programming_language"
> seed com faker

- app/models/gig.rb
- app/models/slot.rb
- app/views/shared/_navbar.html.erb
- app/views/slots/index.html.erb
- db/schema.rb
- test/models/gig_test.rb
> Create silo slots

- app/models/slot.rb
- db/seeds.rb
changed seeds.rb to sample from an array of programming languages as well as changed the model slot to only accept from this same array
> Change to seeds

- app/views/layouts/application.html.erb
changed application.html.erb by removing alert tag, because it was being duplicated in the site
> change application.html.erb

- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/slots/index.html.erb
changed navbar to remove link to new gig page
> navbar changes

- config/routes.rb
gig´s route adicionado dentro de slot
> gig´s route adicionado dentro de slot

- app/controllers/pages_controller.rb
- app/controllers/slots_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/slots/index.html.erb
- db/seeds.rb
added changes to home view and index controller to view commands only when logged in and be able to filter slots by programming language
> added filter options on home page

- app/controllers/slots_controller.rb
> end adicionado

- app/controllers/gigs_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/slots_controller.rb
- app/models/gig.rb
- app/views/gigs/_gig_form.html.erb
- app/views/pages/home.html.erb
- app/views/slots/_slot_form.html.erb
- app/views/slots/index.html.erb
- app/views/slots/show.html.erb
- config/routes.rb
changes to some links and additions to qol stuff while editing and creating new using _slot_form. As well as some changes to both slots and gigs controllers
> Qol changes

- app/controllers/users_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/slots/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
criei o show de users e coloquei no dropdown "my profile" para redirecionar para ele
> fiz o show de user e adicionei o adicionei no dropdown

- app/controllers/gigs_controller.rb
- app/views/gigs/_gig_form.html.erb
- app/views/gigs/new.html.erb
- config/routes.rb
- dropped stashed
- Got Gig to work!!!!!!!!
> 50 urgentverificar route gig e fazer com que seja possível adicionar slots dentro de uma gig

- app/assets/stylesheets/_main.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card_category.scss
- app/assets/stylesheets/components/_card_product.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/slots/_slot_form.html.erb
- app/views/slots/index.html.erb
css changes, as well as qol changes
> Color changes

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_my_gig.scss
- app/assets/stylesheets/components/_my_slot.scss
- app/models/slot.rb
- app/views/gigs/hired.html.erb
- app/views/slots/owned.html.erb
changed style for listing slots and gigs
> list style

- app/assets/stylesheets/_main.scss
removed body code that was messing up site style
> fixed body

- app/controllers/slots_controller.rb
changed controller with conditions to list only the items that have not been bought
> only listing items not bought

- app/assets/stylesheets/components/_search_form.scss
changed searchbar and searchbutton margin colors to better fit the website
> changed margin colors

- app/controllers/gigs_controller.rb
- app/views/gigs/edit.html.erb
- app/views/gigs/hired.html.erb
- app/views/gigs/show.html.erb
- config/routes.rb
- db/seeds.rb
> CRUD gig ok

- app/assets/stylesheets/components/_card_category.scss
- app/views/gigs/hired.html.erb
- app/views/pages/home.html.erb
- app/views/slots/index.html.erb
- app/views/slots/owned.html.erb
- app/views/slots/show.html.erb
- db/schema.rb
> icons fixed

- app/assets/stylesheets/components/_badge_pill.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_item_show.scss
- app/views/gigs/show.html.erb
- app/views/slots/show.html.erb
changed icon size on index and show
> Change icon size on index

- app/assets/stylesheets/config/_fonts.scss
- app/views/layouts/application.html.erb
> changed headers font to Inter

- app/assets/stylesheets/components/_card_product.scss
- app/assets/stylesheets/components/_form_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_margin_left_10.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_item_show.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/gigs/_gig_form.html.erb
- app/views/gigs/new.html.erb
- app/views/slots/_slot_form.html.erb
- app/views/slots/new.html.erb
- app/views/slots/show.html.erb
added form framing and colored programming languages icons on slots#show
> Form change

- app/views/slots/index.html.erb
- app/views/slots/show.html.erb
added breadcrumbs to index and show
> added breadcrumbs
